from typing import Any

def assert_equal(actual, expected, msg=...) -> Any: ...

def assert_not_equal(actual, expected, msg=...) -> Any: ...

def assert_true(val, msg=...) -> Any: ...

def assert_false(val, msg=...) -> Any: ...

def assert_none(val, msg=...) -> Any: ...

def assert_not_none(val, msg=...) -> Any: ...

def assert_close(actual, expected, tolerance=..., msg=...) -> Any: ...

def assert_raises(callable_fn, exception_type, msg=...) -> Any: ...

def assert_tag_value(tag_path, expected, msg=...) -> Any: ...

def assert_contains(container, item, msg=...) -> Any: ...

def assert_isinstance(obj, expected_type, msg=...) -> Any: ...

class TestAssertionError(AssertionError):
    def __init__(self, message, actual=..., expected=...) -> Any: ...