from typing import Any

def run_all(base_package=...) -> Any: ...

def run_module(module_path) -> Any: ...

def _discover_test_modules() -> Any: ...

def _walk_for_tests(directory, base_dir, modules, seen) -> Any: ...

def _import_module(module_path) -> Any: ...

def _run_single_test(name, func) -> Any: ...